apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-data
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.hl.local
    path: "/mnt/dados/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-config
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.hl.local
    path: "/mnt/dados/gitlab/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-logs
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.hl.local
    path: "/mnt/dados/gitlab/logs"
