apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Mi
  volumeName: "gitlab-pv-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Mi
  volumeName: "gitlab-pv-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Mi
  volumeName: "gitlab-pv-logs"
